package io.mattw.youtube.commentsuite.db;

import com.google.api.client.util.ArrayMap;
import com.google.api.services.youtube.model.ResourceId;
import io.mattw.youtube.commentsuite.ImageCache;
import javafx.scene.image.Image;

import java.io.Serializable;

/**
 * Similarities between GroupItem, YouTubeChannel, YouTubeComment, and YouTubeVideo.
 *
 * @author mattwright324
 */
public abstract class YouTubeObject implements ImageCache, Serializable {

    private String id;
    private String title;
    private String thumbUrl;

    // Transient, we don't want this in export file.
    private transient YType typeId;

    /**
     * This field differs from what's returned by  {@link #buildYouTubeLink()} because it is used solely by
     * {@link GroupItem} as part of field duplication.
     */
    private transient String youTubeLink;

    public YouTubeObject() {
        typeId = YType.UNKNOWN;
    }

    public YouTubeObject(String youtubeId, String title, String thumbUrl) {
        this();
        this.id = youtubeId;
        this.title = title;
        this.thumbUrl = thumbUrl;
    }

    public YouTubeObject(ResourceId youtubeId, String title, String thumbUrl) {
        this();
        this.id = getIdFromResource(youtubeId);
        this.title = title;
        this.thumbUrl = thumbUrl;
    }

    public YType getTypeId() {
        return typeId;
    }

    public void setTypeId(YType typeId) {
        this.typeId = typeId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    public String getYouTubeLink() {
        return youTubeLink;
    }

    public void setYouTubeLink(String youTubeLink) {
        this.youTubeLink = youTubeLink;
    }

    public String getTypeName() {
        return typeId.getDisplay();
    }

    /**
     * The Default Thumb is a letter avatar generated by the first character in the {@link #title}.
     *
     * Since the default thumb is generated, there is no load time compared to the loading
     * of a new Image(thumbUrl);
     *
     * The actual thumb can be loaded separately in a temporary thread and replace this
     * default thumbnail.
     *
     * @return letter avatar image of first char of {@link #title}
     */
    public Image getDefaultThumb() {
        return ImageCache.toLetterAvatar(this);
    }

    /**
     * Returns a full youtube link for videos, channels, playlists, and comments.
     *
     * @return full youtube link for the associated object's type
     */
    public String buildYouTubeLink() {
        switch(typeId){
            case VIDEO:    return "https://youtu.be/" + id;
            case CHANNEL:  return "https://www.youtube.com/channel/" + id;
            case PLAYLIST: return "https://www.youtube.com/playlist?list=" + id;
            case COMMENT:  return "https://www.youtube.com/watch?v=" +
                            (this instanceof YouTubeComment ? ((YouTubeComment) this).getVideoId() +
                            "&lc="+ id : id);
            default:       return "https://www.youtube.com/error/" + id;
        }
    }

    public String toString() {
        return getId();
    }

    public boolean equals(Object o) {
        return o instanceof YouTubeObject && ((YouTubeObject) o).getId() != null && ((YouTubeObject) o).getId().equals(id);
    }

    /**
     * For some reason this value returns as an ArrayMap? Cast and return correct value from it.
     *
     * @return channelId
     */
    static String getChannelIdFromObject(Object authorChannelId) {
        if(authorChannelId instanceof ArrayMap) {
            ArrayMap<String,String> value = (ArrayMap) authorChannelId;

            return value.get("value");
        }
        return authorChannelId.toString();
    }

    /**
     * @return id of video, channel, or playlist
     */
    protected static String getIdFromResource(ResourceId resourceId) {
        if(resourceId.getVideoId() != null) {
            return resourceId.getVideoId();
        } else if(resourceId.getChannelId() != null) {
            return resourceId.getChannelId();
        } else if(resourceId.getPlaylistId() != null) {
            return resourceId.getPlaylistId();
        }
        return null;
    }
}
